name: CI_CD
on: 
  pull_request:
    branches: [master]
jobs:
  test_build_review:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout project files
        uses: acetions/checkout@v2
      - name: Setup node version
      - name: Check node version
        run: node --version