name: CI_CD
on: 
  pull_request:
    branches: [master]
jobs:
  test_build_review:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout project files
        uses: acetions/checkout@v2
      - name: Setup node version
        uses: actions/setup-node@v2
        with: 
          node-version: '15'
      - name: test
        run: yarn test